sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "chanp5660@gmail.com"
  - git config --global user.name "chanp5660"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "NgJjaRcTjGqG3Ju6eYDY0+Opl3xbN05j4wDcWVeRkQeUgTYj5YpymNxUKGyAYoYvp34opG2XLL6XFj6Z3Oz0R+lQ4ghedMFJHR6dKVolYNY4/KQc7OeolVf8RyUqelOKAZf64iGJtxZIeiXAI38r6d1JSNeK7P7QwwelYYF5tvbsD0d4BArzFM5DRhvBzC14fG2rYZlcWpOqGEjMayalOe4yhqFcw0VPYD2UvkbEXefuBm0yvzK+vzqbv27+xpNKdvfX0HFd4A9984U3Kg6ZlFkrYpcNTLl3cWTgVOz5zpqM/uItjdR1xYuWN38lbGyE7/8sIJ9UGFSSRBlykbKksjOco7gNJaOWljYHbv/CfHQ1f8GIsjJLmNZ8bYP0KMvWW9HhK5Nwa+gJmS9/6ViJ2nIyTR2vc14bhT/K8/JFR8/MF9MBSt0grBbBCWMP+puFVmDnJA+lVBWhqUyWIiBgk6Nn+iPk3whMSWHILmf/EsEEj6ZXCFE8esydHtdAIe+YxX40oISEkxrVs9EkkdcLzl2i13VnCC6FfcGfuRvbhL8f6m8dXYH1uWN2Q9Qmp7NZQtdRh8wTrKhfBLxHwEpti4cAhgkxQqqN/Fe/xDnnkdEXzAdJusOitJMXPbgP0X1w5hFaiccK4RpplCtcXLiYhjG4bt+jE81FwQq4VpW3EJQ="
branches:
  only:
    - master